name: Qodana

on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/qodana.yml

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: composer install
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v1.0-eap
        with:
          report-dir: docs # GitHub Pages 用に指定
      - name: Count changes
        id: changes
        run: |
          git add -N docs
          echo "::set-output name=count::$(git diff --name-only docs | wc -l)"
      - name: Deploy to GitHub Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Qodana report"
          git push
        if: steps.changes.outputs.count > 0
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: qodana
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: docs
