name: Qodana

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/qodana.yml
    tags:
      - 'pr-test-*'
  pull_request:
    tags:
      - 'pr-test-*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create Report Dir'
        run: |
          mkdir -p docs
      stage: deploy
        image:
          name: jetbrains/qodana:2020.3-eap
          entrypoint: [ "" ]
        script:
          - /opt/idea/bin/entrypoint --results-dir=$CI_PROJECT_DIR/qodana --save-report --report-dir=$CI_PROJECT_DIR/qodana/report
          - ls -la
          - mv docs/ public
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./docs
         destination_dir: ./docs
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: qodana
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: docs
