name: Qodana

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/qodana.yml
    tags:
      - 'pr-test-*'
  pull_request:
    tags:
      - 'pr-test-*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    env:
      GRAZIE_PLUGIN: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=152587
    steps:
      - uses: actions/checkout@v2
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v4.2.5
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qodana/report
          destination_dir: ./
