name: Qodana

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/qodana.yml
    tags:
      - 'pr-test-*'
  pull_request:
    tags:
      - 'pr-test-*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create Report Dir'
        run: |
          mkdir -p docs
      - name: Qodana - Code Inspection
        run: docker run -v ${GITHUB_WORKSPACE}:/data/project -v ${GITHUB_WORKSPACE}/qodana:/data/results JetBrains/qodana-action@v4.2.5 --save-report
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./docs
         destination_dir: ./docs
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: qodana
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: docs
