name: TestQodana

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/qodana.yml
    tags:
      - 'pr-test-*'
  pull_request:
    tags:
      - 'pr-test-*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    env:
      GRAZIE_PLUGIN: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=152587
    steps:
      - uses: actions/checkout@v2
      - name: 'Qodana - Code Inspection'
        uses: JetBrains/qodana-action@v4.2.2
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/qodana
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: 'artifact'
          path: qodana
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qodana/report
          destination_dir: ./
