name: Qodana

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/qodana.yml
    tags:
      - 'pr-test-*'
  pull_request:
    tags:
      - 'pr-test-*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    env:
      GRAZIE_PLUGIN: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=152587
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -L -o grazie-pro.zip "$GRAZIE_PLUGIN" && unzip grazie-pro.zip 
          mv grazie-pro ${{ runner.temp }}/grazie-pro && rm -f grazie-pro.zip
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v4.2.2
        with:
          linter: jetbrains/qodana-js
          additional-volumes: |
            ${{ runner.temp }}/grazie-pro:/opt/idea/plugins/grazie-pro
          report-dir: docs
      - name: Deploy to GitHub Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Qodana report"
          git push
        if: steps.changes.outputs.count > 0
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: qodana
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: docs
